// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: archiveInner.proto

package inner_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举
type Code int32

const (
	Code_Unknown                   Code = 0    // 未知
	Code_Success                   Code = 200  // 成功
	Code_BidErr                    Code = 701  // 业务标识错误
	Code_UserNotExistErr           Code = 720  // 用户不存在
	Code_ParamsErr                 Code = 732  // 请求参数错误
	Code_DisAbnormalNotAbnormalErr Code = 1001 // 解除黑名单 用户非黑名单
	Code_WebDestroyCodeExpiredErr  Code = 1101 // 销毁账号 Code码过期
	Code_WebDestroyCodeErr         Code = 1102 // 销毁账号 Code码错误
	Code_WebDestroyCodeNotFoundErr Code = 1103 // 销毁账号 Code码未生成
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:    "Unknown",
		200:  "Success",
		701:  "BidErr",
		720:  "UserNotExistErr",
		732:  "ParamsErr",
		1001: "DisAbnormalNotAbnormalErr",
		1101: "WebDestroyCodeExpiredErr",
		1102: "WebDestroyCodeErr",
		1103: "WebDestroyCodeNotFoundErr",
	}
	Code_value = map[string]int32{
		"Unknown":                   0,
		"Success":                   200,
		"BidErr":                    701,
		"UserNotExistErr":           720,
		"ParamsErr":                 732,
		"DisAbnormalNotAbnormalErr": 1001,
		"WebDestroyCodeExpiredErr":  1101,
		"WebDestroyCodeErr":         1102,
		"WebDestroyCodeNotFoundErr": 1103,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_archiveInner_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_archiveInner_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{0}
}

// 封装无参数无响应定义
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_archiveInner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{0}
}

type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`  // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`  // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"` // 存档aid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_archiveInner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfo) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *BaseInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BaseInfo) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type DeleteArchiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *BaseInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArchiveReq) Reset() {
	*x = DeleteArchiveReq{}
	mi := &file_archiveInner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchiveReq) ProtoMessage() {}

func (x *DeleteArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchiveReq.ProtoReflect.Descriptor instead.
func (*DeleteArchiveReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteArchiveReq) GetUserInfo() *BaseInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ClearArchiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *BaseInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearArchiveReq) Reset() {
	*x = ClearArchiveReq{}
	mi := &file_archiveInner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearArchiveReq) ProtoMessage() {}

func (x *ClearArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearArchiveReq.ProtoReflect.Descriptor instead.
func (*ClearArchiveReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{3}
}

func (x *ClearArchiveReq) GetUserInfo() *BaseInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type QueryIPForbidUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"` // 存档uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIPForbidUserReq) Reset() {
	*x = QueryIPForbidUserReq{}
	mi := &file_archiveInner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIPForbidUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIPForbidUserReq) ProtoMessage() {}

func (x *QueryIPForbidUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIPForbidUserReq.ProtoReflect.Descriptor instead.
func (*QueryIPForbidUserReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{4}
}

func (x *QueryIPForbidUserReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *QueryIPForbidUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type QueryIPForbidUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         []*IPForbidUserInfo    `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIPForbidUserResp) Reset() {
	*x = QueryIPForbidUserResp{}
	mi := &file_archiveInner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIPForbidUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIPForbidUserResp) ProtoMessage() {}

func (x *QueryIPForbidUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIPForbidUserResp.ProtoReflect.Descriptor instead.
func (*QueryIPForbidUserResp) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{5}
}

func (x *QueryIPForbidUserResp) GetLists() []*IPForbidUserInfo {
	if x != nil {
		return x.Lists
	}
	return nil
}

type IPForbidUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`   // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`   // 存档uid
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`     // 访问 IP
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"` // 时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPForbidUserInfo) Reset() {
	*x = IPForbidUserInfo{}
	mi := &file_archiveInner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPForbidUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPForbidUserInfo) ProtoMessage() {}

func (x *IPForbidUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPForbidUserInfo.ProtoReflect.Descriptor instead.
func (*IPForbidUserInfo) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{6}
}

func (x *IPForbidUserInfo) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *IPForbidUserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *IPForbidUserInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPForbidUserInfo) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DisAbnormalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`        // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`        // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`       // 存档id
	Action        int32                  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"` // 默认为主动解封 action = 0 被动解封 action = 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisAbnormalReq) Reset() {
	*x = DisAbnormalReq{}
	mi := &file_archiveInner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisAbnormalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisAbnormalReq) ProtoMessage() {}

func (x *DisAbnormalReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisAbnormalReq.ProtoReflect.Descriptor instead.
func (*DisAbnormalReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{7}
}

func (x *DisAbnormalReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *DisAbnormalReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DisAbnormalReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *DisAbnormalReq) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type WebDestroyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`   // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`   // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`  // 存档id
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` // code验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebDestroyReq) Reset() {
	*x = WebDestroyReq{}
	mi := &file_archiveInner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebDestroyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebDestroyReq) ProtoMessage() {}

func (x *WebDestroyReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebDestroyReq.ProtoReflect.Descriptor instead.
func (*WebDestroyReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{8}
}

func (x *WebDestroyReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *WebDestroyReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WebDestroyReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *WebDestroyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BatchAbnuserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`        // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`        // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`       // 存档id
	Reason        int32                  `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"` // 黑名单原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAbnuserReq) Reset() {
	*x = BatchAbnuserReq{}
	mi := &file_archiveInner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAbnuserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAbnuserReq) ProtoMessage() {}

func (x *BatchAbnuserReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAbnuserReq.ProtoReflect.Descriptor instead.
func (*BatchAbnuserReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{9}
}

func (x *BatchAbnuserReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *BatchAbnuserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BatchAbnuserReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *BatchAbnuserReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type BatchAbnuserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAbnuserResp) Reset() {
	*x = BatchAbnuserResp{}
	mi := &file_archiveInner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAbnuserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAbnuserResp) ProtoMessage() {}

func (x *BatchAbnuserResp) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAbnuserResp.ProtoReflect.Descriptor instead.
func (*BatchAbnuserResp) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{10}
}

func (x *BatchAbnuserResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Unknown
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"` // 存档uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_archiveInner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserInfoReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserSocialInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`  // 社交id
	Aid           int32                  `protobuf:"varint,2,opt,name=aid,proto3" json:"aid,omitempty"` // 存档id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSocialInfo) Reset() {
	*x = UserSocialInfo{}
	mi := &file_archiveInner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSocialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSocialInfo) ProtoMessage() {}

func (x *UserSocialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSocialInfo.ProtoReflect.Descriptor instead.
func (*UserSocialInfo) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{12}
}

func (x *UserSocialInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *UserSocialInfo) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                         // 存档uid
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`                         // 设备id
	RegTime       int64                  `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"` // 注册时间
	List          []*UserSocialInfo      `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`                       // 社交注册信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_archiveInner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoResp) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetUserInfoResp) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *GetUserInfoResp) GetList() []*UserSocialInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetUserInfoDidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"` // 设备id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoDidReq) Reset() {
	*x = GetUserInfoDidReq{}
	mi := &file_archiveInner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoDidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoDidReq) ProtoMessage() {}

func (x *GetUserInfoDidReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoDidReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoDidReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInfoDidReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoDidReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetUserInfoDidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                         // 存档uid
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`                         // 设备id
	RegTime       int64                  `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"` // 注册时间
	List          []*UserSocialInfo      `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`                       // 社交注册信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoDidResp) Reset() {
	*x = GetUserInfoDidResp{}
	mi := &file_archiveInner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoDidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoDidResp) ProtoMessage() {}

func (x *GetUserInfoDidResp) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoDidResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoDidResp) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserInfoDidResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoDidResp) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetUserInfoDidResp) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *GetUserInfoDidResp) GetList() []*UserSocialInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ModifyArchiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`     // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`     // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`    // 存档id
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`     // 修改key
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // 修改value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyArchiveReq) Reset() {
	*x = ModifyArchiveReq{}
	mi := &file_archiveInner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyArchiveReq) ProtoMessage() {}

func (x *ModifyArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyArchiveReq.ProtoReflect.Descriptor instead.
func (*ModifyArchiveReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{16}
}

func (x *ModifyArchiveReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *ModifyArchiveReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ModifyArchiveReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *ModifyArchiveReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModifyArchiveReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetUserInfoByKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 用户key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByKeyReq) Reset() {
	*x = GetUserInfoByKeyReq{}
	mi := &file_archiveInner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByKeyReq) ProtoMessage() {}

func (x *GetUserInfoByKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByKeyReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoByKeyReq) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserInfoByKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetUserInfoByKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`  // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`  // 存档uid
	Aid           int32                  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"` // 存档id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByKeyResp) Reset() {
	*x = GetUserInfoByKeyResp{}
	mi := &file_archiveInner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByKeyResp) ProtoMessage() {}

func (x *GetUserInfoByKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_archiveInner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByKeyResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoByKeyResp) Descriptor() ([]byte, []int) {
	return file_archiveInner_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserInfoByKeyResp) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoByKeyResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoByKeyResp) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

var File_archiveInner_proto protoreflect.FileDescriptor

const file_archiveInner_proto_rawDesc = "" +
	"\n" +
	"\x12archiveInner.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"@\n" +
	"\bBaseInfo\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid\":\n" +
	"\x10DeleteArchiveReq\x12&\n" +
	"\tuser_info\x18\x01 \x01(\v2\t.BaseInfoR\buserInfo\"9\n" +
	"\x0fClearArchiveReq\x12&\n" +
	"\tuser_info\x18\x01 \x01(\v2\t.BaseInfoR\buserInfo\":\n" +
	"\x14QueryIPForbidUserReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"@\n" +
	"\x15QueryIPForbidUserResp\x12'\n" +
	"\x05lists\x18\x01 \x03(\v2\x11.IPForbidUserInfoR\x05lists\"v\n" +
	"\x10IPForbidUserInfo\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"^\n" +
	"\x0eDisAbnormalReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid\x12\x16\n" +
	"\x06action\x18\x04 \x01(\x05R\x06action\"Y\n" +
	"\rWebDestroyReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"_\n" +
	"\x0fBatchAbnuserReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\x05R\x06reason\"-\n" +
	"\x10BatchAbnuserResp\x12\x19\n" +
	"\x04code\x18\x01 \x01(\x0e2\x05.CodeR\x04code\"4\n" +
	"\x0eGetUserInfoReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"4\n" +
	"\x0eUserSocialInfo\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03aid\x18\x02 \x01(\x05R\x03aid\"u\n" +
	"\x0fGetUserInfoResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x19\n" +
	"\breg_time\x18\x03 \x01(\x03R\aregTime\x12#\n" +
	"\x04list\x18\x04 \x03(\v2\x0f.UserSocialInfoR\x04list\"7\n" +
	"\x11GetUserInfoDidReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\"x\n" +
	"\x12GetUserInfoDidResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x19\n" +
	"\breg_time\x18\x03 \x01(\x03R\aregTime\x12#\n" +
	"\x04list\x18\x04 \x03(\v2\x0f.UserSocialInfoR\x04list\"p\n" +
	"\x10ModifyArchiveReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"'\n" +
	"\x13GetUserInfoByKeyReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\x14GetUserInfoByKeyResp\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x10\n" +
	"\x03aid\x18\x03 \x01(\x05R\x03aid*\xcb\x01\n" +
	"\x04Code\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\aSuccess\x10\xc8\x01\x12\v\n" +
	"\x06BidErr\x10\xbd\x05\x12\x14\n" +
	"\x0fUserNotExistErr\x10\xd0\x05\x12\x0e\n" +
	"\tParamsErr\x10\xdc\x05\x12\x1e\n" +
	"\x19DisAbnormalNotAbnormalErr\x10\xe9\a\x12\x1d\n" +
	"\x18WebDestroyCodeExpiredErr\x10\xcd\b\x12\x16\n" +
	"\x11WebDestroyCodeErr\x10\xce\b\x12\x1e\n" +
	"\x19WebDestroyCodeNotFoundErr\x10\xcf\b2\x9d\x04\n" +
	"\fArchiveInner\x12(\n" +
	"\vDisAbnormal\x12\x0f.DisAbnormalReq\x1a\x06.Empty\"\x00\x12&\n" +
	"\n" +
	"WebDestroy\x12\x0e.WebDestroyReq\x1a\x06.Empty\"\x00\x129\n" +
	"\fBatchAbnuser\x12\x10.BatchAbnuserReq\x1a\x11.BatchAbnuserResp\"\x00(\x010\x01\x122\n" +
	"\vGetUserInfo\x12\x0f.GetUserInfoReq\x1a\x10.GetUserInfoResp\"\x00\x12;\n" +
	"\x0eGetUserInfoDid\x12\x12.GetUserInfoDidReq\x1a\x13.GetUserInfoDidResp\"\x00\x12,\n" +
	"\rModifyArchive\x12\x11.ModifyArchiveReq\x1a\x06.Empty\"\x00\x12A\n" +
	"\x10GetUserInfoByKey\x12\x14.GetUserInfoByKeyReq\x1a\x15.GetUserInfoByKeyResp\"\x00\x12D\n" +
	"\x11QueryIPForbidUser\x12\x15.QueryIPForbidUserReq\x1a\x16.QueryIPForbidUserResp\"\x00\x12*\n" +
	"\fClearArchive\x12\x10.ClearArchiveReq\x1a\x06.Empty\"\x00\x12,\n" +
	"\rDeleteArchive\x12\x11.DeleteArchiveReq\x1a\x06.Empty\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_archiveInner_proto_rawDescOnce sync.Once
	file_archiveInner_proto_rawDescData []byte
)

func file_archiveInner_proto_rawDescGZIP() []byte {
	file_archiveInner_proto_rawDescOnce.Do(func() {
		file_archiveInner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_archiveInner_proto_rawDesc), len(file_archiveInner_proto_rawDesc)))
	})
	return file_archiveInner_proto_rawDescData
}

var file_archiveInner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_archiveInner_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_archiveInner_proto_goTypes = []any{
	(Code)(0),                     // 0: Code
	(*Empty)(nil),                 // 1: Empty
	(*BaseInfo)(nil),              // 2: BaseInfo
	(*DeleteArchiveReq)(nil),      // 3: DeleteArchiveReq
	(*ClearArchiveReq)(nil),       // 4: ClearArchiveReq
	(*QueryIPForbidUserReq)(nil),  // 5: QueryIPForbidUserReq
	(*QueryIPForbidUserResp)(nil), // 6: QueryIPForbidUserResp
	(*IPForbidUserInfo)(nil),      // 7: IPForbidUserInfo
	(*DisAbnormalReq)(nil),        // 8: DisAbnormalReq
	(*WebDestroyReq)(nil),         // 9: WebDestroyReq
	(*BatchAbnuserReq)(nil),       // 10: BatchAbnuserReq
	(*BatchAbnuserResp)(nil),      // 11: BatchAbnuserResp
	(*GetUserInfoReq)(nil),        // 12: GetUserInfoReq
	(*UserSocialInfo)(nil),        // 13: UserSocialInfo
	(*GetUserInfoResp)(nil),       // 14: GetUserInfoResp
	(*GetUserInfoDidReq)(nil),     // 15: GetUserInfoDidReq
	(*GetUserInfoDidResp)(nil),    // 16: GetUserInfoDidResp
	(*ModifyArchiveReq)(nil),      // 17: ModifyArchiveReq
	(*GetUserInfoByKeyReq)(nil),   // 18: GetUserInfoByKeyReq
	(*GetUserInfoByKeyResp)(nil),  // 19: GetUserInfoByKeyResp
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_archiveInner_proto_depIdxs = []int32{
	2,  // 0: DeleteArchiveReq.user_info:type_name -> BaseInfo
	2,  // 1: ClearArchiveReq.user_info:type_name -> BaseInfo
	7,  // 2: QueryIPForbidUserResp.lists:type_name -> IPForbidUserInfo
	20, // 3: IPForbidUserInfo.time:type_name -> google.protobuf.Timestamp
	0,  // 4: BatchAbnuserResp.code:type_name -> Code
	13, // 5: GetUserInfoResp.list:type_name -> UserSocialInfo
	13, // 6: GetUserInfoDidResp.list:type_name -> UserSocialInfo
	8,  // 7: ArchiveInner.DisAbnormal:input_type -> DisAbnormalReq
	9,  // 8: ArchiveInner.WebDestroy:input_type -> WebDestroyReq
	10, // 9: ArchiveInner.BatchAbnuser:input_type -> BatchAbnuserReq
	12, // 10: ArchiveInner.GetUserInfo:input_type -> GetUserInfoReq
	15, // 11: ArchiveInner.GetUserInfoDid:input_type -> GetUserInfoDidReq
	17, // 12: ArchiveInner.ModifyArchive:input_type -> ModifyArchiveReq
	18, // 13: ArchiveInner.GetUserInfoByKey:input_type -> GetUserInfoByKeyReq
	5,  // 14: ArchiveInner.QueryIPForbidUser:input_type -> QueryIPForbidUserReq
	4,  // 15: ArchiveInner.ClearArchive:input_type -> ClearArchiveReq
	3,  // 16: ArchiveInner.DeleteArchive:input_type -> DeleteArchiveReq
	1,  // 17: ArchiveInner.DisAbnormal:output_type -> Empty
	1,  // 18: ArchiveInner.WebDestroy:output_type -> Empty
	11, // 19: ArchiveInner.BatchAbnuser:output_type -> BatchAbnuserResp
	14, // 20: ArchiveInner.GetUserInfo:output_type -> GetUserInfoResp
	16, // 21: ArchiveInner.GetUserInfoDid:output_type -> GetUserInfoDidResp
	1,  // 22: ArchiveInner.ModifyArchive:output_type -> Empty
	19, // 23: ArchiveInner.GetUserInfoByKey:output_type -> GetUserInfoByKeyResp
	6,  // 24: ArchiveInner.QueryIPForbidUser:output_type -> QueryIPForbidUserResp
	1,  // 25: ArchiveInner.ClearArchive:output_type -> Empty
	1,  // 26: ArchiveInner.DeleteArchive:output_type -> Empty
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_archiveInner_proto_init() }
func file_archiveInner_proto_init() {
	if File_archiveInner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_archiveInner_proto_rawDesc), len(file_archiveInner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_archiveInner_proto_goTypes,
		DependencyIndexes: file_archiveInner_proto_depIdxs,
		EnumInfos:         file_archiveInner_proto_enumTypes,
		MessageInfos:      file_archiveInner_proto_msgTypes,
	}.Build()
	File_archiveInner_proto = out.File
	file_archiveInner_proto_goTypes = nil
	file_archiveInner_proto_depIdxs = nil
}
