// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: rankInner.proto

package inner_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RankSystemClient is the client API for RankSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankSystemClient interface {
	// 后台踢人
	KickUser(ctx context.Context, in *KickUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取用户排名
	GetUserRank(ctx context.Context, in *GetUserRankReq, opts ...grpc.CallOption) (*GetUserRankResp, error)
}

type rankSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewRankSystemClient(cc grpc.ClientConnInterface) RankSystemClient {
	return &rankSystemClient{cc}
}

func (c *rankSystemClient) KickUser(ctx context.Context, in *KickUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/RankApi.RankSystem/KickUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankSystemClient) GetUserRank(ctx context.Context, in *GetUserRankReq, opts ...grpc.CallOption) (*GetUserRankResp, error) {
	out := new(GetUserRankResp)
	err := c.cc.Invoke(ctx, "/RankApi.RankSystem/GetUserRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankSystemServer is the server API for RankSystem service.
// All implementations must embed UnimplementedRankSystemServer
// for forward compatibility
type RankSystemServer interface {
	// 后台踢人
	KickUser(context.Context, *KickUserReq) (*emptypb.Empty, error)
	// 获取用户排名
	GetUserRank(context.Context, *GetUserRankReq) (*GetUserRankResp, error)
	mustEmbedUnimplementedRankSystemServer()
}

// UnimplementedRankSystemServer must be embedded to have forward compatible implementations.
type UnimplementedRankSystemServer struct {
}

func (UnimplementedRankSystemServer) KickUser(context.Context, *KickUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickUser not implemented")
}
func (UnimplementedRankSystemServer) GetUserRank(context.Context, *GetUserRankReq) (*GetUserRankResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRank not implemented")
}
func (UnimplementedRankSystemServer) mustEmbedUnimplementedRankSystemServer() {}

// UnsafeRankSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankSystemServer will
// result in compilation errors.
type UnsafeRankSystemServer interface {
	mustEmbedUnimplementedRankSystemServer()
}

func RegisterRankSystemServer(s grpc.ServiceRegistrar, srv RankSystemServer) {
	s.RegisterService(&RankSystem_ServiceDesc, srv)
}

func _RankSystem_KickUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankSystemServer).KickUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RankApi.RankSystem/KickUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankSystemServer).KickUser(ctx, req.(*KickUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankSystem_GetUserRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRankReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankSystemServer).GetUserRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RankApi.RankSystem/GetUserRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankSystemServer).GetUserRank(ctx, req.(*GetUserRankReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RankSystem_ServiceDesc is the grpc.ServiceDesc for RankSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RankApi.RankSystem",
	HandlerType: (*RankSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KickUser",
			Handler:    _RankSystem_KickUser_Handler,
		},
		{
			MethodName: "GetUserRank",
			Handler:    _RankSystem_GetUserRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rankInner.proto",
}
