// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: rankInner.proto

package inner_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`                            // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                            // 用户id
	RankId        string                 `protobuf:"bytes,3,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`        // 榜单id 不传踢所有榜单
	KickType      int32                  `protobuf:"varint,4,opt,name=kick_type,json=kickType,proto3" json:"kick_type,omitempty"` // 0: 踢人 1: 不可在进入榜单
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_rankInner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_rankInner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_rankInner_proto_rawDescGZIP(), []int{0}
}

func (x *KickUserReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *KickUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KickUserReq) GetRankId() string {
	if x != nil {
		return x.RankId
	}
	return ""
}

func (x *KickUserReq) GetKickType() int32 {
	if x != nil {
		return x.KickType
	}
	return 0
}

type GetUserRankReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`                     // 业务标识
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                     // 用户id
	RankId        string                 `protobuf:"bytes,3,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"` // 榜单id 不传获取所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankReq) Reset() {
	*x = GetUserRankReq{}
	mi := &file_rankInner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankReq) ProtoMessage() {}

func (x *GetUserRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_rankInner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankReq.ProtoReflect.Descriptor instead.
func (*GetUserRankReq) Descriptor() ([]byte, []int) {
	return file_rankInner_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRankReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserRankReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserRankReq) GetRankId() string {
	if x != nil {
		return x.RankId
	}
	return ""
}

type RankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankId        string                 `protobuf:"bytes,1,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	RankKey       string                 `protobuf:"bytes,5,opt,name=rank_key,json=rankKey,proto3" json:"rank_key,omitempty"` // 榜单key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankInfo) Reset() {
	*x = RankInfo{}
	mi := &file_rankInner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankInfo) ProtoMessage() {}

func (x *RankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rankInner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankInfo.ProtoReflect.Descriptor instead.
func (*RankInfo) Descriptor() ([]byte, []int) {
	return file_rankInner_proto_rawDescGZIP(), []int{2}
}

func (x *RankInfo) GetRankId() string {
	if x != nil {
		return x.RankId
	}
	return ""
}

func (x *RankInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RankInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankInfo) GetRankKey() string {
	if x != nil {
		return x.RankKey
	}
	return ""
}

type GetUserRankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankInfo      []*RankInfo            `protobuf:"bytes,1,rep,name=rank_info,json=rankInfo,proto3" json:"rank_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRankResp) Reset() {
	*x = GetUserRankResp{}
	mi := &file_rankInner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRankResp) ProtoMessage() {}

func (x *GetUserRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_rankInner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRankResp.ProtoReflect.Descriptor instead.
func (*GetUserRankResp) Descriptor() ([]byte, []int) {
	return file_rankInner_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRankResp) GetRankInfo() []*RankInfo {
	if x != nil {
		return x.RankInfo
	}
	return nil
}

var File_rankInner_proto protoreflect.FileDescriptor

const file_rankInner_proto_rawDesc = "" +
	"\n" +
	"\x0frankInner.proto\x12\aRankApi\x1a\x1bgoogle/protobuf/empty.proto\"g\n" +
	"\vKickUserReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x17\n" +
	"\arank_id\x18\x03 \x01(\tR\x06rankId\x12\x1b\n" +
	"\tkick_type\x18\x04 \x01(\x05R\bkickType\"M\n" +
	"\x0eGetUserRankReq\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x17\n" +
	"\arank_id\x18\x03 \x01(\tR\x06rankId\"z\n" +
	"\bRankInfo\x12\x17\n" +
	"\arank_id\x18\x01 \x01(\tR\x06rankId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x19\n" +
	"\brank_key\x18\x05 \x01(\tR\arankKey\"A\n" +
	"\x0fGetUserRankResp\x12.\n" +
	"\trank_info\x18\x01 \x03(\v2\x11.RankApi.RankInfoR\brankInfo2\x8c\x01\n" +
	"\n" +
	"RankSystem\x12:\n" +
	"\bKickUser\x12\x14.RankApi.KickUserReq\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vGetUserRank\x12\x17.RankApi.GetUserRankReq\x1a\x18.RankApi.GetUserRankResp\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_rankInner_proto_rawDescOnce sync.Once
	file_rankInner_proto_rawDescData []byte
)

func file_rankInner_proto_rawDescGZIP() []byte {
	file_rankInner_proto_rawDescOnce.Do(func() {
		file_rankInner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rankInner_proto_rawDesc), len(file_rankInner_proto_rawDesc)))
	})
	return file_rankInner_proto_rawDescData
}

var file_rankInner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rankInner_proto_goTypes = []any{
	(*KickUserReq)(nil),     // 0: RankApi.KickUserReq
	(*GetUserRankReq)(nil),  // 1: RankApi.GetUserRankReq
	(*RankInfo)(nil),        // 2: RankApi.RankInfo
	(*GetUserRankResp)(nil), // 3: RankApi.GetUserRankResp
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_rankInner_proto_depIdxs = []int32{
	2, // 0: RankApi.GetUserRankResp.rank_info:type_name -> RankApi.RankInfo
	0, // 1: RankApi.RankSystem.KickUser:input_type -> RankApi.KickUserReq
	1, // 2: RankApi.RankSystem.GetUserRank:input_type -> RankApi.GetUserRankReq
	4, // 3: RankApi.RankSystem.KickUser:output_type -> google.protobuf.Empty
	3, // 4: RankApi.RankSystem.GetUserRank:output_type -> RankApi.GetUserRankResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rankInner_proto_init() }
func file_rankInner_proto_init() {
	if File_rankInner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rankInner_proto_rawDesc), len(file_rankInner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rankInner_proto_goTypes,
		DependencyIndexes: file_rankInner_proto_depIdxs,
		MessageInfos:      file_rankInner_proto_msgTypes,
	}.Build()
	File_rankInner_proto = out.File
	file_rankInner_proto_goTypes = nil
	file_rankInner_proto_depIdxs = nil
}
