// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: proto/archiveInner.proto

package inner_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举
type Code int32

const (
	Code_Unknown                   Code = 0    // 未知
	Code_Success                   Code = 200  // 成功
	Code_BidErr                    Code = 701  // 业务标识错误
	Code_UserNotExistErr           Code = 720  // 用户不存在
	Code_ParamsErr                 Code = 732  // 请求参数错误
	Code_DisAbnormalNotAbnormalErr Code = 1001 // 解除黑名单 用户非黑名单
	Code_WebDestroyCodeExpiredErr  Code = 1101 // 销毁账号 Code码过期
	Code_WebDestroyCodeErr         Code = 1102 // 销毁账号 Code码错误
	Code_WebDestroyCodeNotFoundErr Code = 1103 // 销毁账号 Code码未生成
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:    "Unknown",
		200:  "Success",
		701:  "BidErr",
		720:  "UserNotExistErr",
		732:  "ParamsErr",
		1001: "DisAbnormalNotAbnormalErr",
		1101: "WebDestroyCodeExpiredErr",
		1102: "WebDestroyCodeErr",
		1103: "WebDestroyCodeNotFoundErr",
	}
	Code_value = map[string]int32{
		"Unknown":                   0,
		"Success":                   200,
		"BidErr":                    701,
		"UserNotExistErr":           720,
		"ParamsErr":                 732,
		"DisAbnormalNotAbnormalErr": 1001,
		"WebDestroyCodeExpiredErr":  1101,
		"WebDestroyCodeErr":         1102,
		"WebDestroyCodeNotFoundErr": 1103,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_archiveInner_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_proto_archiveInner_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{0}
}

// 封装无参数无响应定义
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{0}
}

type BaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`  // 业务标识
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`  // 存档uid
	Aid int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"` // 存档aid
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfo) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *BaseInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BaseInfo) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type DeleteArchiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *BaseInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
}

func (x *DeleteArchiveReq) Reset() {
	*x = DeleteArchiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchiveReq) ProtoMessage() {}

func (x *DeleteArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchiveReq.ProtoReflect.Descriptor instead.
func (*DeleteArchiveReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteArchiveReq) GetUserInfo() *BaseInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ClearArchiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *BaseInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
}

func (x *ClearArchiveReq) Reset() {
	*x = ClearArchiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearArchiveReq) ProtoMessage() {}

func (x *ClearArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearArchiveReq.ProtoReflect.Descriptor instead.
func (*ClearArchiveReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{3}
}

func (x *ClearArchiveReq) GetUserInfo() *BaseInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type QueryIPForbidUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"` // 存档uid
}

func (x *QueryIPForbidUserReq) Reset() {
	*x = QueryIPForbidUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIPForbidUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIPForbidUserReq) ProtoMessage() {}

func (x *QueryIPForbidUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIPForbidUserReq.ProtoReflect.Descriptor instead.
func (*QueryIPForbidUserReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{4}
}

func (x *QueryIPForbidUserReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *QueryIPForbidUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type QueryIPForbidUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lists []*IPForbidUserInfo `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
}

func (x *QueryIPForbidUserResp) Reset() {
	*x = QueryIPForbidUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIPForbidUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIPForbidUserResp) ProtoMessage() {}

func (x *QueryIPForbidUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIPForbidUserResp.ProtoReflect.Descriptor instead.
func (*QueryIPForbidUserResp) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{5}
}

func (x *QueryIPForbidUserResp) GetLists() []*IPForbidUserInfo {
	if x != nil {
		return x.Lists
	}
	return nil
}

type IPForbidUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid  string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`   // 业务标识
	Uid  string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`   // 存档uid
	Ip   string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`     // 访问 IP
	Time *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"` // 时间
}

func (x *IPForbidUserInfo) Reset() {
	*x = IPForbidUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPForbidUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPForbidUserInfo) ProtoMessage() {}

func (x *IPForbidUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPForbidUserInfo.ProtoReflect.Descriptor instead.
func (*IPForbidUserInfo) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{6}
}

func (x *IPForbidUserInfo) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *IPForbidUserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *IPForbidUserInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPForbidUserInfo) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DisAbnormalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid    string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`        // 业务标识
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`        // 存档uid
	Aid    int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`       // 存档id
	Action int32  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"` // 默认为主动解封 action = 0 被动解封 action = 1
}

func (x *DisAbnormalReq) Reset() {
	*x = DisAbnormalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisAbnormalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisAbnormalReq) ProtoMessage() {}

func (x *DisAbnormalReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisAbnormalReq.ProtoReflect.Descriptor instead.
func (*DisAbnormalReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{7}
}

func (x *DisAbnormalReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *DisAbnormalReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DisAbnormalReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *DisAbnormalReq) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type WebDestroyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid  string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`   // 业务标识
	Uid  string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`   // 存档uid
	Aid  int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`  // 存档id
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` // code验证码
}

func (x *WebDestroyReq) Reset() {
	*x = WebDestroyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebDestroyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebDestroyReq) ProtoMessage() {}

func (x *WebDestroyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebDestroyReq.ProtoReflect.Descriptor instead.
func (*WebDestroyReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{8}
}

func (x *WebDestroyReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *WebDestroyReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WebDestroyReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *WebDestroyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BatchAbnuserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid    string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`        // 业务标识
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`        // 存档uid
	Aid    int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`       // 存档id
	Reason int32  `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"` // 黑名单原因
}

func (x *BatchAbnuserReq) Reset() {
	*x = BatchAbnuserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchAbnuserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAbnuserReq) ProtoMessage() {}

func (x *BatchAbnuserReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAbnuserReq.ProtoReflect.Descriptor instead.
func (*BatchAbnuserReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{9}
}

func (x *BatchAbnuserReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *BatchAbnuserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BatchAbnuserReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *BatchAbnuserReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type BatchAbnuserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
}

func (x *BatchAbnuserResp) Reset() {
	*x = BatchAbnuserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchAbnuserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAbnuserResp) ProtoMessage() {}

func (x *BatchAbnuserResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAbnuserResp.ProtoReflect.Descriptor instead.
func (*BatchAbnuserResp) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{10}
}

func (x *BatchAbnuserResp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Unknown
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"` // 存档uid
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserInfoReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserSocialInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`  // 社交id
	Aid int32  `protobuf:"varint,2,opt,name=aid,proto3" json:"aid,omitempty"` // 存档id
}

func (x *UserSocialInfo) Reset() {
	*x = UserSocialInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSocialInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSocialInfo) ProtoMessage() {}

func (x *UserSocialInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSocialInfo.ProtoReflect.Descriptor instead.
func (*UserSocialInfo) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{12}
}

func (x *UserSocialInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *UserSocialInfo) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                         // 存档uid
	Did     string            `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`                         // 设备id
	RegTime int64             `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"` // 注册时间
	List    []*UserSocialInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`                       // 社交注册信息
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoResp) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetUserInfoResp) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *GetUserInfoResp) GetList() []*UserSocialInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetUserInfoDidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"` // 业务标识
	Did string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"` // 设备id
}

func (x *GetUserInfoDidReq) Reset() {
	*x = GetUserInfoDidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoDidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoDidReq) ProtoMessage() {}

func (x *GetUserInfoDidReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoDidReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoDidReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInfoDidReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoDidReq) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetUserInfoDidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                         // 存档uid
	Did     string            `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`                         // 设备id
	RegTime int64             `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"` // 注册时间
	List    []*UserSocialInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`                       // 社交注册信息
}

func (x *GetUserInfoDidResp) Reset() {
	*x = GetUserInfoDidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoDidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoDidResp) ProtoMessage() {}

func (x *GetUserInfoDidResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoDidResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoDidResp) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserInfoDidResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoDidResp) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetUserInfoDidResp) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *GetUserInfoDidResp) GetList() []*UserSocialInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ModifyArchiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid   string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`     // 业务标识
	Uid   string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`     // 存档uid
	Aid   int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`    // 存档id
	Key   string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`     // 修改key
	Value string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // 修改value
}

func (x *ModifyArchiveReq) Reset() {
	*x = ModifyArchiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyArchiveReq) ProtoMessage() {}

func (x *ModifyArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyArchiveReq.ProtoReflect.Descriptor instead.
func (*ModifyArchiveReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{16}
}

func (x *ModifyArchiveReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *ModifyArchiveReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ModifyArchiveReq) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *ModifyArchiveReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModifyArchiveReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetUserInfoByKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 用户key
}

func (x *GetUserInfoByKeyReq) Reset() {
	*x = GetUserInfoByKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByKeyReq) ProtoMessage() {}

func (x *GetUserInfoByKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByKeyReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoByKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserInfoByKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetUserInfoByKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`  // 业务标识
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`  // 存档uid
	Aid int32  `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"` // 存档id
}

func (x *GetUserInfoByKeyResp) Reset() {
	*x = GetUserInfoByKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByKeyResp) ProtoMessage() {}

func (x *GetUserInfoByKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByKeyResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoByKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserInfoByKeyResp) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetUserInfoByKeyResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetUserInfoByKeyResp) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

// 奖励发放请求
type RewardGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid     string             `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`                                                                                                   // 业务标识
	Uid     string             `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                                   // 用户ID
	Aid     int32              `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`                                                                                                  // 存档ID
	Rewards map[string]float32 `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"` // 奖励信息
}

func (x *RewardGrantRequest) Reset() {
	*x = RewardGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardGrantRequest) ProtoMessage() {}

func (x *RewardGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardGrantRequest.ProtoReflect.Descriptor instead.
func (*RewardGrantRequest) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{19}
}

func (x *RewardGrantRequest) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *RewardGrantRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RewardGrantRequest) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *RewardGrantRequest) GetRewards() map[string]float32 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 奖励发放响应
type RewardGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates map[string]float32 `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"` //更新后的资产信息
}

func (x *RewardGrantResponse) Reset() {
	*x = RewardGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_archiveInner_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardGrantResponse) ProtoMessage() {}

func (x *RewardGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archiveInner_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardGrantResponse.ProtoReflect.Descriptor instead.
func (*RewardGrantResponse) Descriptor() ([]byte, []int) {
	return file_proto_archiveInner_proto_rawDescGZIP(), []int{20}
}

func (x *RewardGrantResponse) GetUpdates() map[string]float32 {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_proto_archiveInner_proto protoreflect.FileDescriptor

var file_proto_archiveInner_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x40, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3a, 0x0a,
	0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x50, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x15, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x50, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x49, 0x50, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x22, 0x76, 0x0a, 0x10, 0x49,
	0x50, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a, 0x0d, 0x57, 0x65, 0x62, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x5f,
	0x0a, 0x0f, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x62, 0x6e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x2d, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x62, 0x6e, 0x75, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x05, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x34,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x44, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x78, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x70, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x4c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x22, 0xc2, 0x01,
	0x0a, 0x12, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x2a, 0xcb, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x10, 0xc8, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x42, 0x69, 0x64, 0x45, 0x72,
	0x72, 0x10, 0xbd, 0x05, 0x12, 0x14, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x10, 0xd0, 0x05, 0x12, 0x0e, 0x0a, 0x09, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x45, 0x72, 0x72, 0x10, 0xdc, 0x05, 0x12, 0x1e, 0x0a, 0x19, 0x44, 0x69,
	0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x4e, 0x6f, 0x74, 0x41, 0x62, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x10, 0xe9, 0x07, 0x12, 0x1d, 0x0a, 0x18, 0x57, 0x65,
	0x62, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x45, 0x72, 0x72, 0x10, 0xcd, 0x08, 0x12, 0x16, 0x0a, 0x11, 0x57, 0x65, 0x62,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x10, 0xce,
	0x08, 0x12, 0x1e, 0x0a, 0x19, 0x57, 0x65, 0x62, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x43,
	0x6f, 0x64, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x10, 0xcf,
	0x08, 0x32, 0xd5, 0x04, 0x0a, 0x0c, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x12, 0x0f, 0x2e, 0x44, 0x69, 0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0a,
	0x57, 0x65, 0x62, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x0e, 0x2e, 0x57, 0x65, 0x62,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x62, 0x6e,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x62, 0x6e, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x41, 0x62,
	0x6e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x69, 0x64, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x12, 0x11, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x50, 0x46, 0x6f, 0x72, 0x62,
	0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x50,
	0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x50, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x12, 0x10, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70,
	0x62, 0x3b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_archiveInner_proto_rawDescOnce sync.Once
	file_proto_archiveInner_proto_rawDescData = file_proto_archiveInner_proto_rawDesc
)

func file_proto_archiveInner_proto_rawDescGZIP() []byte {
	file_proto_archiveInner_proto_rawDescOnce.Do(func() {
		file_proto_archiveInner_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_archiveInner_proto_rawDescData)
	})
	return file_proto_archiveInner_proto_rawDescData
}

var file_proto_archiveInner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_archiveInner_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_archiveInner_proto_goTypes = []any{
	(Code)(0),                     // 0: Code
	(*Empty)(nil),                 // 1: Empty
	(*BaseInfo)(nil),              // 2: BaseInfo
	(*DeleteArchiveReq)(nil),      // 3: DeleteArchiveReq
	(*ClearArchiveReq)(nil),       // 4: ClearArchiveReq
	(*QueryIPForbidUserReq)(nil),  // 5: QueryIPForbidUserReq
	(*QueryIPForbidUserResp)(nil), // 6: QueryIPForbidUserResp
	(*IPForbidUserInfo)(nil),      // 7: IPForbidUserInfo
	(*DisAbnormalReq)(nil),        // 8: DisAbnormalReq
	(*WebDestroyReq)(nil),         // 9: WebDestroyReq
	(*BatchAbnuserReq)(nil),       // 10: BatchAbnuserReq
	(*BatchAbnuserResp)(nil),      // 11: BatchAbnuserResp
	(*GetUserInfoReq)(nil),        // 12: GetUserInfoReq
	(*UserSocialInfo)(nil),        // 13: UserSocialInfo
	(*GetUserInfoResp)(nil),       // 14: GetUserInfoResp
	(*GetUserInfoDidReq)(nil),     // 15: GetUserInfoDidReq
	(*GetUserInfoDidResp)(nil),    // 16: GetUserInfoDidResp
	(*ModifyArchiveReq)(nil),      // 17: ModifyArchiveReq
	(*GetUserInfoByKeyReq)(nil),   // 18: GetUserInfoByKeyReq
	(*GetUserInfoByKeyResp)(nil),  // 19: GetUserInfoByKeyResp
	(*RewardGrantRequest)(nil),    // 20: RewardGrantRequest
	(*RewardGrantResponse)(nil),   // 21: RewardGrantResponse
	nil,                           // 22: RewardGrantRequest.RewardsEntry
	nil,                           // 23: RewardGrantResponse.UpdatesEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_proto_archiveInner_proto_depIdxs = []int32{
	2,  // 0: DeleteArchiveReq.user_info:type_name -> BaseInfo
	2,  // 1: ClearArchiveReq.user_info:type_name -> BaseInfo
	7,  // 2: QueryIPForbidUserResp.lists:type_name -> IPForbidUserInfo
	24, // 3: IPForbidUserInfo.time:type_name -> google.protobuf.Timestamp
	0,  // 4: BatchAbnuserResp.code:type_name -> Code
	13, // 5: GetUserInfoResp.list:type_name -> UserSocialInfo
	13, // 6: GetUserInfoDidResp.list:type_name -> UserSocialInfo
	22, // 7: RewardGrantRequest.rewards:type_name -> RewardGrantRequest.RewardsEntry
	23, // 8: RewardGrantResponse.updates:type_name -> RewardGrantResponse.UpdatesEntry
	8,  // 9: ArchiveInner.DisAbnormal:input_type -> DisAbnormalReq
	9,  // 10: ArchiveInner.WebDestroy:input_type -> WebDestroyReq
	10, // 11: ArchiveInner.BatchAbnuser:input_type -> BatchAbnuserReq
	12, // 12: ArchiveInner.GetUserInfo:input_type -> GetUserInfoReq
	15, // 13: ArchiveInner.GetUserInfoDid:input_type -> GetUserInfoDidReq
	17, // 14: ArchiveInner.ModifyArchive:input_type -> ModifyArchiveReq
	18, // 15: ArchiveInner.GetUserInfoByKey:input_type -> GetUserInfoByKeyReq
	5,  // 16: ArchiveInner.QueryIPForbidUser:input_type -> QueryIPForbidUserReq
	4,  // 17: ArchiveInner.ClearArchive:input_type -> ClearArchiveReq
	3,  // 18: ArchiveInner.DeleteArchive:input_type -> DeleteArchiveReq
	20, // 19: ArchiveInner.Rewards:input_type -> RewardGrantRequest
	1,  // 20: ArchiveInner.DisAbnormal:output_type -> Empty
	1,  // 21: ArchiveInner.WebDestroy:output_type -> Empty
	11, // 22: ArchiveInner.BatchAbnuser:output_type -> BatchAbnuserResp
	14, // 23: ArchiveInner.GetUserInfo:output_type -> GetUserInfoResp
	16, // 24: ArchiveInner.GetUserInfoDid:output_type -> GetUserInfoDidResp
	1,  // 25: ArchiveInner.ModifyArchive:output_type -> Empty
	19, // 26: ArchiveInner.GetUserInfoByKey:output_type -> GetUserInfoByKeyResp
	6,  // 27: ArchiveInner.QueryIPForbidUser:output_type -> QueryIPForbidUserResp
	1,  // 28: ArchiveInner.ClearArchive:output_type -> Empty
	1,  // 29: ArchiveInner.DeleteArchive:output_type -> Empty
	21, // 30: ArchiveInner.Rewards:output_type -> RewardGrantResponse
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_archiveInner_proto_init() }
func file_proto_archiveInner_proto_init() {
	if File_proto_archiveInner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_archiveInner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteArchiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ClearArchiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*QueryIPForbidUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*QueryIPForbidUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*IPForbidUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DisAbnormalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*WebDestroyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BatchAbnuserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BatchAbnuserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UserSocialInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoDidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoDidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyArchiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoByKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserInfoByKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RewardGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_archiveInner_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*RewardGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_archiveInner_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_archiveInner_proto_goTypes,
		DependencyIndexes: file_proto_archiveInner_proto_depIdxs,
		EnumInfos:         file_proto_archiveInner_proto_enumTypes,
		MessageInfos:      file_proto_archiveInner_proto_msgTypes,
	}.Build()
	File_proto_archiveInner_proto = out.File
	file_proto_archiveInner_proto_rawDesc = nil
	file_proto_archiveInner_proto_goTypes = nil
	file_proto_archiveInner_proto_depIdxs = nil
}
