// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: proto/archiveInner.proto

package inner_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArchiveInner_DisAbnormal_FullMethodName       = "/ArchiveInner/DisAbnormal"
	ArchiveInner_WebDestroy_FullMethodName        = "/ArchiveInner/WebDestroy"
	ArchiveInner_BatchAbnuser_FullMethodName      = "/ArchiveInner/BatchAbnuser"
	ArchiveInner_GetUserInfo_FullMethodName       = "/ArchiveInner/GetUserInfo"
	ArchiveInner_GetUserInfoDid_FullMethodName    = "/ArchiveInner/GetUserInfoDid"
	ArchiveInner_ModifyArchive_FullMethodName     = "/ArchiveInner/ModifyArchive"
	ArchiveInner_GetUserInfoByKey_FullMethodName  = "/ArchiveInner/GetUserInfoByKey"
	ArchiveInner_QueryIPForbidUser_FullMethodName = "/ArchiveInner/QueryIPForbidUser"
	ArchiveInner_ClearArchive_FullMethodName      = "/ArchiveInner/ClearArchive"
	ArchiveInner_DeleteArchive_FullMethodName     = "/ArchiveInner/DeleteArchive"
	ArchiveInner_Rewards_FullMethodName           = "/ArchiveInner/Rewards"
)

// ArchiveInnerClient is the client API for ArchiveInner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 存档内部API接口定义
type ArchiveInnerClient interface {
	DisAbnormal(ctx context.Context, in *DisAbnormalReq, opts ...grpc.CallOption) (*Empty, error)
	WebDestroy(ctx context.Context, in *WebDestroyReq, opts ...grpc.CallOption) (*Empty, error)
	BatchAbnuser(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchAbnuserReq, BatchAbnuserResp], error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	GetUserInfoDid(ctx context.Context, in *GetUserInfoDidReq, opts ...grpc.CallOption) (*GetUserInfoDidResp, error)
	ModifyArchive(ctx context.Context, in *ModifyArchiveReq, opts ...grpc.CallOption) (*Empty, error)
	GetUserInfoByKey(ctx context.Context, in *GetUserInfoByKeyReq, opts ...grpc.CallOption) (*GetUserInfoByKeyResp, error)
	QueryIPForbidUser(ctx context.Context, in *QueryIPForbidUserReq, opts ...grpc.CallOption) (*QueryIPForbidUserResp, error)
	ClearArchive(ctx context.Context, in *ClearArchiveReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteArchive(ctx context.Context, in *DeleteArchiveReq, opts ...grpc.CallOption) (*Empty, error)
	Rewards(ctx context.Context, in *RewardGrantRequest, opts ...grpc.CallOption) (*RewardGrantResponse, error)
}

type archiveInnerClient struct {
	cc grpc.ClientConnInterface
}

func NewArchiveInnerClient(cc grpc.ClientConnInterface) ArchiveInnerClient {
	return &archiveInnerClient{cc}
}

func (c *archiveInnerClient) DisAbnormal(ctx context.Context, in *DisAbnormalReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ArchiveInner_DisAbnormal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) WebDestroy(ctx context.Context, in *WebDestroyReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ArchiveInner_WebDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) BatchAbnuser(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchAbnuserReq, BatchAbnuserResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArchiveInner_ServiceDesc.Streams[0], ArchiveInner_BatchAbnuser_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchAbnuserReq, BatchAbnuserResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArchiveInner_BatchAbnuserClient = grpc.BidiStreamingClient[BatchAbnuserReq, BatchAbnuserResp]

func (c *archiveInnerClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, ArchiveInner_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) GetUserInfoDid(ctx context.Context, in *GetUserInfoDidReq, opts ...grpc.CallOption) (*GetUserInfoDidResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoDidResp)
	err := c.cc.Invoke(ctx, ArchiveInner_GetUserInfoDid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) ModifyArchive(ctx context.Context, in *ModifyArchiveReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ArchiveInner_ModifyArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) GetUserInfoByKey(ctx context.Context, in *GetUserInfoByKeyReq, opts ...grpc.CallOption) (*GetUserInfoByKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoByKeyResp)
	err := c.cc.Invoke(ctx, ArchiveInner_GetUserInfoByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) QueryIPForbidUser(ctx context.Context, in *QueryIPForbidUserReq, opts ...grpc.CallOption) (*QueryIPForbidUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryIPForbidUserResp)
	err := c.cc.Invoke(ctx, ArchiveInner_QueryIPForbidUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) ClearArchive(ctx context.Context, in *ClearArchiveReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ArchiveInner_ClearArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) DeleteArchive(ctx context.Context, in *DeleteArchiveReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ArchiveInner_DeleteArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *archiveInnerClient) Rewards(ctx context.Context, in *RewardGrantRequest, opts ...grpc.CallOption) (*RewardGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewardGrantResponse)
	err := c.cc.Invoke(ctx, ArchiveInner_Rewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveInnerServer is the server API for ArchiveInner service.
// All implementations must embed UnimplementedArchiveInnerServer
// for forward compatibility.
//
// 存档内部API接口定义
type ArchiveInnerServer interface {
	DisAbnormal(context.Context, *DisAbnormalReq) (*Empty, error)
	WebDestroy(context.Context, *WebDestroyReq) (*Empty, error)
	BatchAbnuser(grpc.BidiStreamingServer[BatchAbnuserReq, BatchAbnuserResp]) error
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	GetUserInfoDid(context.Context, *GetUserInfoDidReq) (*GetUserInfoDidResp, error)
	ModifyArchive(context.Context, *ModifyArchiveReq) (*Empty, error)
	GetUserInfoByKey(context.Context, *GetUserInfoByKeyReq) (*GetUserInfoByKeyResp, error)
	QueryIPForbidUser(context.Context, *QueryIPForbidUserReq) (*QueryIPForbidUserResp, error)
	ClearArchive(context.Context, *ClearArchiveReq) (*Empty, error)
	DeleteArchive(context.Context, *DeleteArchiveReq) (*Empty, error)
	Rewards(context.Context, *RewardGrantRequest) (*RewardGrantResponse, error)
	mustEmbedUnimplementedArchiveInnerServer()
}

// UnimplementedArchiveInnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchiveInnerServer struct{}

func (UnimplementedArchiveInnerServer) DisAbnormal(context.Context, *DisAbnormalReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DisAbnormal not implemented")
}
func (UnimplementedArchiveInnerServer) WebDestroy(context.Context, *WebDestroyReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WebDestroy not implemented")
}
func (UnimplementedArchiveInnerServer) BatchAbnuser(grpc.BidiStreamingServer[BatchAbnuserReq, BatchAbnuserResp]) error {
	return status.Error(codes.Unimplemented, "method BatchAbnuser not implemented")
}
func (UnimplementedArchiveInnerServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedArchiveInnerServer) GetUserInfoDid(context.Context, *GetUserInfoDidReq) (*GetUserInfoDidResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfoDid not implemented")
}
func (UnimplementedArchiveInnerServer) ModifyArchive(context.Context, *ModifyArchiveReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyArchive not implemented")
}
func (UnimplementedArchiveInnerServer) GetUserInfoByKey(context.Context, *GetUserInfoByKeyReq) (*GetUserInfoByKeyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfoByKey not implemented")
}
func (UnimplementedArchiveInnerServer) QueryIPForbidUser(context.Context, *QueryIPForbidUserReq) (*QueryIPForbidUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryIPForbidUser not implemented")
}
func (UnimplementedArchiveInnerServer) ClearArchive(context.Context, *ClearArchiveReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearArchive not implemented")
}
func (UnimplementedArchiveInnerServer) DeleteArchive(context.Context, *DeleteArchiveReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArchive not implemented")
}
func (UnimplementedArchiveInnerServer) Rewards(context.Context, *RewardGrantRequest) (*RewardGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rewards not implemented")
}
func (UnimplementedArchiveInnerServer) mustEmbedUnimplementedArchiveInnerServer() {}
func (UnimplementedArchiveInnerServer) testEmbeddedByValue()                      {}

// UnsafeArchiveInnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchiveInnerServer will
// result in compilation errors.
type UnsafeArchiveInnerServer interface {
	mustEmbedUnimplementedArchiveInnerServer()
}

func RegisterArchiveInnerServer(s grpc.ServiceRegistrar, srv ArchiveInnerServer) {
	// If the following call panics, it indicates UnimplementedArchiveInnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchiveInner_ServiceDesc, srv)
}

func _ArchiveInner_DisAbnormal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisAbnormalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).DisAbnormal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_DisAbnormal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).DisAbnormal(ctx, req.(*DisAbnormalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_WebDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebDestroyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).WebDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_WebDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).WebDestroy(ctx, req.(*WebDestroyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_BatchAbnuser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArchiveInnerServer).BatchAbnuser(&grpc.GenericServerStream[BatchAbnuserReq, BatchAbnuserResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArchiveInner_BatchAbnuserServer = grpc.BidiStreamingServer[BatchAbnuserReq, BatchAbnuserResp]

func _ArchiveInner_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_GetUserInfoDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoDidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).GetUserInfoDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_GetUserInfoDid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).GetUserInfoDid(ctx, req.(*GetUserInfoDidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_ModifyArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyArchiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).ModifyArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_ModifyArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).ModifyArchive(ctx, req.(*ModifyArchiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_GetUserInfoByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoByKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).GetUserInfoByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_GetUserInfoByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).GetUserInfoByKey(ctx, req.(*GetUserInfoByKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_QueryIPForbidUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIPForbidUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).QueryIPForbidUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_QueryIPForbidUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).QueryIPForbidUser(ctx, req.(*QueryIPForbidUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_ClearArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearArchiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).ClearArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_ClearArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).ClearArchive(ctx, req.(*ClearArchiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_DeleteArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArchiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).DeleteArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_DeleteArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).DeleteArchive(ctx, req.(*DeleteArchiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArchiveInner_Rewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewardGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveInnerServer).Rewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveInner_Rewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveInnerServer).Rewards(ctx, req.(*RewardGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchiveInner_ServiceDesc is the grpc.ServiceDesc for ArchiveInner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchiveInner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ArchiveInner",
	HandlerType: (*ArchiveInnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisAbnormal",
			Handler:    _ArchiveInner_DisAbnormal_Handler,
		},
		{
			MethodName: "WebDestroy",
			Handler:    _ArchiveInner_WebDestroy_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _ArchiveInner_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfoDid",
			Handler:    _ArchiveInner_GetUserInfoDid_Handler,
		},
		{
			MethodName: "ModifyArchive",
			Handler:    _ArchiveInner_ModifyArchive_Handler,
		},
		{
			MethodName: "GetUserInfoByKey",
			Handler:    _ArchiveInner_GetUserInfoByKey_Handler,
		},
		{
			MethodName: "QueryIPForbidUser",
			Handler:    _ArchiveInner_QueryIPForbidUser_Handler,
		},
		{
			MethodName: "ClearArchive",
			Handler:    _ArchiveInner_ClearArchive_Handler,
		},
		{
			MethodName: "DeleteArchive",
			Handler:    _ArchiveInner_DeleteArchive_Handler,
		},
		{
			MethodName: "Rewards",
			Handler:    _ArchiveInner_Rewards_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchAbnuser",
			Handler:       _ArchiveInner_BatchAbnuser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/archiveInner.proto",
}
