// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: coreAsset.proto

package inner_grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetGoeInner_Rewards_FullMethodName = "/AssetGoeInner/Rewards"
)

// AssetGoeInnerClient is the client API for AssetGoeInner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 内部API接口定义
type AssetGoeInnerClient interface {
	Rewards(ctx context.Context, in *RewardGrantRequest, opts ...grpc.CallOption) (*RewardGrantResponse, error)
}

type assetGoeInnerClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetGoeInnerClient(cc grpc.ClientConnInterface) AssetGoeInnerClient {
	return &assetGoeInnerClient{cc}
}

func (c *assetGoeInnerClient) Rewards(ctx context.Context, in *RewardGrantRequest, opts ...grpc.CallOption) (*RewardGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewardGrantResponse)
	err := c.cc.Invoke(ctx, AssetGoeInner_Rewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetGoeInnerServer is the server API for AssetGoeInner service.
// All implementations must embed UnimplementedAssetGoeInnerServer
// for forward compatibility.
//
// 内部API接口定义
type AssetGoeInnerServer interface {
	Rewards(context.Context, *RewardGrantRequest) (*RewardGrantResponse, error)
	mustEmbedUnimplementedAssetGoeInnerServer()
}

// UnimplementedAssetGoeInnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetGoeInnerServer struct{}

func (UnimplementedAssetGoeInnerServer) Rewards(context.Context, *RewardGrantRequest) (*RewardGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rewards not implemented")
}
func (UnimplementedAssetGoeInnerServer) mustEmbedUnimplementedAssetGoeInnerServer() {}
func (UnimplementedAssetGoeInnerServer) testEmbeddedByValue()                       {}

// UnsafeAssetGoeInnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetGoeInnerServer will
// result in compilation errors.
type UnsafeAssetGoeInnerServer interface {
	mustEmbedUnimplementedAssetGoeInnerServer()
}

func RegisterAssetGoeInnerServer(s grpc.ServiceRegistrar, srv AssetGoeInnerServer) {
	// If the following call panics, it indicates UnimplementedAssetGoeInnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetGoeInner_ServiceDesc, srv)
}

func _AssetGoeInner_Rewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewardGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetGoeInnerServer).Rewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetGoeInner_Rewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetGoeInnerServer).Rewards(ctx, req.(*RewardGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetGoeInner_ServiceDesc is the grpc.ServiceDesc for AssetGoeInner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetGoeInner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AssetGoeInner",
	HandlerType: (*AssetGoeInnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rewards",
			Handler:    _AssetGoeInner_Rewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coreAsset.proto",
}
