// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: coreAsset.proto

package inner_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 奖励发放请求
type RewardGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid     string           `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`                                                                                                  // 业务标识
	Uid     string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                                  // 用户ID
	Aid     int32            `protobuf:"varint,3,opt,name=aid,proto3" json:"aid,omitempty"`                                                                                                 // 存档ID
	Rewards map[string]int64 `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 奖励信息
}

func (x *RewardGrantRequest) Reset() {
	*x = RewardGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coreAsset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardGrantRequest) ProtoMessage() {}

func (x *RewardGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coreAsset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardGrantRequest.ProtoReflect.Descriptor instead.
func (*RewardGrantRequest) Descriptor() ([]byte, []int) {
	return file_coreAsset_proto_rawDescGZIP(), []int{0}
}

func (x *RewardGrantRequest) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *RewardGrantRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RewardGrantRequest) GetAid() int32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *RewardGrantRequest) GetRewards() map[string]int64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 奖励发放响应
type RewardGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates map[string]int64 `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //更新后的资产信息
}

func (x *RewardGrantResponse) Reset() {
	*x = RewardGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coreAsset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewardGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardGrantResponse) ProtoMessage() {}

func (x *RewardGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coreAsset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardGrantResponse.ProtoReflect.Descriptor instead.
func (*RewardGrantResponse) Descriptor() ([]byte, []int) {
	return file_coreAsset_proto_rawDescGZIP(), []int{1}
}

func (x *RewardGrantResponse) GetUpdates() map[string]int64 {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_coreAsset_proto protoreflect.FileDescriptor

var file_coreAsset_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x69, 0x64, 0x12, 0x3a,
	0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8e, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x47, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x47, 0x6f, 0x65, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x47, 0x72, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coreAsset_proto_rawDescOnce sync.Once
	file_coreAsset_proto_rawDescData = file_coreAsset_proto_rawDesc
)

func file_coreAsset_proto_rawDescGZIP() []byte {
	file_coreAsset_proto_rawDescOnce.Do(func() {
		file_coreAsset_proto_rawDescData = protoimpl.X.CompressGZIP(file_coreAsset_proto_rawDescData)
	})
	return file_coreAsset_proto_rawDescData
}

var file_coreAsset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_coreAsset_proto_goTypes = []any{
	(*RewardGrantRequest)(nil),  // 0: RewardGrantRequest
	(*RewardGrantResponse)(nil), // 1: RewardGrantResponse
	nil,                         // 2: RewardGrantRequest.RewardsEntry
	nil,                         // 3: RewardGrantResponse.UpdatesEntry
}
var file_coreAsset_proto_depIdxs = []int32{
	2, // 0: RewardGrantRequest.rewards:type_name -> RewardGrantRequest.RewardsEntry
	3, // 1: RewardGrantResponse.updates:type_name -> RewardGrantResponse.UpdatesEntry
	0, // 2: AssetGoeInner.Rewards:input_type -> RewardGrantRequest
	1, // 3: AssetGoeInner.Rewards:output_type -> RewardGrantResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coreAsset_proto_init() }
func file_coreAsset_proto_init() {
	if File_coreAsset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coreAsset_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RewardGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coreAsset_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RewardGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coreAsset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coreAsset_proto_goTypes,
		DependencyIndexes: file_coreAsset_proto_depIdxs,
		MessageInfos:      file_coreAsset_proto_msgTypes,
	}.Build()
	File_coreAsset_proto = out.File
	file_coreAsset_proto_rawDesc = nil
	file_coreAsset_proto_goTypes = nil
	file_coreAsset_proto_depIdxs = nil
}
