// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: proto/FacebookInner.proto

package inner_grpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FacebookSystem_ListRankInfo_FullMethodName      = "/FacebookApi.FacebookSystem/ListRankInfo"
	FacebookSystem_UpdatePlayerScore_FullMethodName = "/FacebookApi.FacebookSystem/UpdatePlayerScore"
)

// FacebookSystemClient is the client API for FacebookSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FacebookSystemClient interface {
	// 获取排位赛数据（对应公共数据 /v1/common/list）
	ListRankInfo(ctx context.Context, in *ListRankInfoReq, opts ...grpc.CallOption) (*ListRankInfoResp, error)
	// 修改用户分数
	UpdatePlayerScore(ctx context.Context, in *UpdatePlayerScoreReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type facebookSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewFacebookSystemClient(cc grpc.ClientConnInterface) FacebookSystemClient {
	return &facebookSystemClient{cc}
}

func (c *facebookSystemClient) ListRankInfo(ctx context.Context, in *ListRankInfoReq, opts ...grpc.CallOption) (*ListRankInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRankInfoResp)
	err := c.cc.Invoke(ctx, FacebookSystem_ListRankInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facebookSystemClient) UpdatePlayerScore(ctx context.Context, in *UpdatePlayerScoreReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FacebookSystem_UpdatePlayerScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacebookSystemServer is the server API for FacebookSystem service.
// All implementations must embed UnimplementedFacebookSystemServer
// for forward compatibility.
type FacebookSystemServer interface {
	// 获取排位赛数据（对应公共数据 /v1/common/list）
	ListRankInfo(context.Context, *ListRankInfoReq) (*ListRankInfoResp, error)
	// 修改用户分数
	UpdatePlayerScore(context.Context, *UpdatePlayerScoreReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedFacebookSystemServer()
}

// UnimplementedFacebookSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFacebookSystemServer struct{}

func (UnimplementedFacebookSystemServer) ListRankInfo(context.Context, *ListRankInfoReq) (*ListRankInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRankInfo not implemented")
}
func (UnimplementedFacebookSystemServer) UpdatePlayerScore(context.Context, *UpdatePlayerScoreReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlayerScore not implemented")
}
func (UnimplementedFacebookSystemServer) mustEmbedUnimplementedFacebookSystemServer() {}
func (UnimplementedFacebookSystemServer) testEmbeddedByValue()                        {}

// UnsafeFacebookSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacebookSystemServer will
// result in compilation errors.
type UnsafeFacebookSystemServer interface {
	mustEmbedUnimplementedFacebookSystemServer()
}

func RegisterFacebookSystemServer(s grpc.ServiceRegistrar, srv FacebookSystemServer) {
	// If the following call panics, it indicates UnimplementedFacebookSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FacebookSystem_ServiceDesc, srv)
}

func _FacebookSystem_ListRankInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRankInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacebookSystemServer).ListRankInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacebookSystem_ListRankInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacebookSystemServer).ListRankInfo(ctx, req.(*ListRankInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacebookSystem_UpdatePlayerScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacebookSystemServer).UpdatePlayerScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacebookSystem_UpdatePlayerScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacebookSystemServer).UpdatePlayerScore(ctx, req.(*UpdatePlayerScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FacebookSystem_ServiceDesc is the grpc.ServiceDesc for FacebookSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FacebookSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FacebookApi.FacebookSystem",
	HandlerType: (*FacebookSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRankInfo",
			Handler:    _FacebookSystem_ListRankInfo_Handler,
		},
		{
			MethodName: "UpdatePlayerScore",
			Handler:    _FacebookSystem_UpdatePlayerScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/FacebookInner.proto",
}
