// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: proto/RankGuildInner.proto

package inner_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页查询公会榜单请求
type GuildRankListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey    string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`          // 业务标识
	RankingId string `protobuf:"bytes,2,opt,name=ranking_id,json=rankingId,proto3" json:"ranking_id,omitempty"` // 榜单id
	Page      int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                           // 页码，从1开始
	PageSize  int64  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页条数
	GuildId   string `protobuf:"bytes,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`       // 公会id（可选，传入则只返回该公会数据）
}

func (x *GuildRankListReq) Reset() {
	*x = GuildRankListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRankListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRankListReq) ProtoMessage() {}

func (x *GuildRankListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRankListReq.ProtoReflect.Descriptor instead.
func (*GuildRankListReq) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{0}
}

func (x *GuildRankListReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *GuildRankListReq) GetRankingId() string {
	if x != nil {
		return x.RankingId
	}
	return ""
}

func (x *GuildRankListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GuildRankListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GuildRankListReq) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

// 公会榜单条目
type InnerGuildRankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RankingKey string `protobuf:"bytes,1,opt,name=ranking_key,json=rankingKey,proto3" json:"ranking_key,omitempty"` // 榜单key
	GuildId    string `protobuf:"bytes,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`          // 公会id
	Rank       int64  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                              // 排名（1-based）
	Score      int64  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                            // 公会总分
}

func (x *InnerGuildRankItem) Reset() {
	*x = InnerGuildRankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerGuildRankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerGuildRankItem) ProtoMessage() {}

func (x *InnerGuildRankItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerGuildRankItem.ProtoReflect.Descriptor instead.
func (*InnerGuildRankItem) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{1}
}

func (x *InnerGuildRankItem) GetRankingKey() string {
	if x != nil {
		return x.RankingKey
	}
	return ""
}

func (x *InnerGuildRankItem) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *InnerGuildRankItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *InnerGuildRankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 分页查询公会榜单响应
type GuildRankListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*InnerGuildRankItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 榜单列表
	Total int64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 榜单总条数
}

func (x *GuildRankListResp) Reset() {
	*x = GuildRankListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildRankListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRankListResp) ProtoMessage() {}

func (x *GuildRankListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRankListResp.ProtoReflect.Descriptor instead.
func (*GuildRankListResp) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{2}
}

func (x *GuildRankListResp) GetList() []*InnerGuildRankItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GuildRankListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查询公会成员贡献分数请求
type GuildMemberRankListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey    string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`          // 业务标识
	RankingId string `protobuf:"bytes,2,opt,name=ranking_id,json=rankingId,proto3" json:"ranking_id,omitempty"` // 榜单id
	GuildId   string `protobuf:"bytes,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`       // 公会id（必填）
	UserId    string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 玩家id（可选，传入则只返回该玩家数据）
	Page      int64  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                           // 页码，从1开始
	PageSize  int64  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页条数
}

func (x *GuildMemberRankListReq) Reset() {
	*x = GuildMemberRankListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildMemberRankListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMemberRankListReq) ProtoMessage() {}

func (x *GuildMemberRankListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMemberRankListReq.ProtoReflect.Descriptor instead.
func (*GuildMemberRankListReq) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{3}
}

func (x *GuildMemberRankListReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *GuildMemberRankListReq) GetRankingId() string {
	if x != nil {
		return x.RankingId
	}
	return ""
}

func (x *GuildMemberRankListReq) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *GuildMemberRankListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GuildMemberRankListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GuildMemberRankListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 成员贡献分数条目
type InnerMemberScoreItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 玩家id
	Score      int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                            // 贡献分数
	RankingKey string `protobuf:"bytes,3,opt,name=ranking_key,json=rankingKey,proto3" json:"ranking_key,omitempty"` // 榜单key
	Rank       int64  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`                              // 排名
}

func (x *InnerMemberScoreItem) Reset() {
	*x = InnerMemberScoreItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerMemberScoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMemberScoreItem) ProtoMessage() {}

func (x *InnerMemberScoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMemberScoreItem.ProtoReflect.Descriptor instead.
func (*InnerMemberScoreItem) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{4}
}

func (x *InnerMemberScoreItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InnerMemberScoreItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *InnerMemberScoreItem) GetRankingKey() string {
	if x != nil {
		return x.RankingKey
	}
	return ""
}

func (x *InnerMemberScoreItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 查询公会成员贡献分数响应
type GuildMemberRankListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*InnerMemberScoreItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 成员分数列表
	Total int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总条数
}

func (x *GuildMemberRankListResp) Reset() {
	*x = GuildMemberRankListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RankGuildInner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildMemberRankListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMemberRankListResp) ProtoMessage() {}

func (x *GuildMemberRankListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RankGuildInner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMemberRankListResp.ProtoReflect.Descriptor instead.
func (*GuildMemberRankListResp) Descriptor() ([]byte, []int) {
	return file_proto_RankGuildInner_proto_rawDescGZIP(), []int{5}
}

func (x *GuildMemberRankListResp) GetList() []*InnerMemberScoreItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GuildMemberRankListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_RankGuildInner_proto protoreflect.FileDescriptor

var file_proto_RankGuildInner_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x52, 0x61,
	0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x69, 0x22, 0x96, 0x01, 0x0a, 0x10, 0x47,
	0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x6b,
	0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x12, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e,
	0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75,
	0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22,
	0x5f, 0x0a, 0x11, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x69, 0x2e, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0xb5, 0x01, 0x0a, 0x16, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x61,
	0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x70, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7a, 0x0a, 0x14, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x22, 0x67, 0x0a, 0x17, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x6e,
	0x65, 0x72, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xcb, 0x01,
	0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1e, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x69, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x69, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x13, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x52,
	0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70, 0x69, 0x2e, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x25, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x70,
	0x69, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x61, 0x6e,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2f, 0x70, 0x62, 0x3b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_RankGuildInner_proto_rawDescOnce sync.Once
	file_proto_RankGuildInner_proto_rawDescData = file_proto_RankGuildInner_proto_rawDesc
)

func file_proto_RankGuildInner_proto_rawDescGZIP() []byte {
	file_proto_RankGuildInner_proto_rawDescOnce.Do(func() {
		file_proto_RankGuildInner_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RankGuildInner_proto_rawDescData)
	})
	return file_proto_RankGuildInner_proto_rawDescData
}

var file_proto_RankGuildInner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_RankGuildInner_proto_goTypes = []any{
	(*GuildRankListReq)(nil),        // 0: RankGuildApi.GuildRankListReq
	(*InnerGuildRankItem)(nil),      // 1: RankGuildApi.InnerGuildRankItem
	(*GuildRankListResp)(nil),       // 2: RankGuildApi.GuildRankListResp
	(*GuildMemberRankListReq)(nil),  // 3: RankGuildApi.GuildMemberRankListReq
	(*InnerMemberScoreItem)(nil),    // 4: RankGuildApi.InnerMemberScoreItem
	(*GuildMemberRankListResp)(nil), // 5: RankGuildApi.GuildMemberRankListResp
}
var file_proto_RankGuildInner_proto_depIdxs = []int32{
	1, // 0: RankGuildApi.GuildRankListResp.list:type_name -> RankGuildApi.InnerGuildRankItem
	4, // 1: RankGuildApi.GuildMemberRankListResp.list:type_name -> RankGuildApi.InnerMemberScoreItem
	0, // 2: RankGuildApi.RankGuildSystem.GuildRankList:input_type -> RankGuildApi.GuildRankListReq
	3, // 3: RankGuildApi.RankGuildSystem.GuildMemberRankList:input_type -> RankGuildApi.GuildMemberRankListReq
	2, // 4: RankGuildApi.RankGuildSystem.GuildRankList:output_type -> RankGuildApi.GuildRankListResp
	5, // 5: RankGuildApi.RankGuildSystem.GuildMemberRankList:output_type -> RankGuildApi.GuildMemberRankListResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_RankGuildInner_proto_init() }
func file_proto_RankGuildInner_proto_init() {
	if File_proto_RankGuildInner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RankGuildInner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GuildRankListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RankGuildInner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InnerGuildRankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RankGuildInner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GuildRankListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RankGuildInner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GuildMemberRankListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RankGuildInner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InnerMemberScoreItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RankGuildInner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GuildMemberRankListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RankGuildInner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_RankGuildInner_proto_goTypes,
		DependencyIndexes: file_proto_RankGuildInner_proto_depIdxs,
		MessageInfos:      file_proto_RankGuildInner_proto_msgTypes,
	}.Build()
	File_proto_RankGuildInner_proto = out.File
	file_proto_RankGuildInner_proto_rawDesc = nil
	file_proto_RankGuildInner_proto_goTypes = nil
	file_proto_RankGuildInner_proto_depIdxs = nil
}
