// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.3
// source: proto/RankGuildInner.proto

package inner_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankGuildSystem_GuildRankList_FullMethodName       = "/RankGuildApi.RankGuildSystem/GuildRankList"
	RankGuildSystem_GuildMemberRankList_FullMethodName = "/RankGuildApi.RankGuildSystem/GuildMemberRankList"
)

// RankGuildSystemClient is the client API for RankGuildSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 给内部系统调用接口
type RankGuildSystemClient interface {
	// 分页查询公会榜单（全球榜/地区榜）
	GuildRankList(ctx context.Context, in *GuildRankListReq, opts ...grpc.CallOption) (*GuildRankListResp, error)
	// 查询公会成员的贡献分数
	GuildMemberRankList(ctx context.Context, in *GuildMemberRankListReq, opts ...grpc.CallOption) (*GuildMemberRankListResp, error)
}

type rankGuildSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewRankGuildSystemClient(cc grpc.ClientConnInterface) RankGuildSystemClient {
	return &rankGuildSystemClient{cc}
}

func (c *rankGuildSystemClient) GuildRankList(ctx context.Context, in *GuildRankListReq, opts ...grpc.CallOption) (*GuildRankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildRankListResp)
	err := c.cc.Invoke(ctx, RankGuildSystem_GuildRankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankGuildSystemClient) GuildMemberRankList(ctx context.Context, in *GuildMemberRankListReq, opts ...grpc.CallOption) (*GuildMemberRankListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildMemberRankListResp)
	err := c.cc.Invoke(ctx, RankGuildSystem_GuildMemberRankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankGuildSystemServer is the server API for RankGuildSystem service.
// All implementations must embed UnimplementedRankGuildSystemServer
// for forward compatibility.
//
// 给内部系统调用接口
type RankGuildSystemServer interface {
	// 分页查询公会榜单（全球榜/地区榜）
	GuildRankList(context.Context, *GuildRankListReq) (*GuildRankListResp, error)
	// 查询公会成员的贡献分数
	GuildMemberRankList(context.Context, *GuildMemberRankListReq) (*GuildMemberRankListResp, error)
	mustEmbedUnimplementedRankGuildSystemServer()
}

// UnimplementedRankGuildSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankGuildSystemServer struct{}

func (UnimplementedRankGuildSystemServer) GuildRankList(context.Context, *GuildRankListReq) (*GuildRankListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GuildRankList not implemented")
}
func (UnimplementedRankGuildSystemServer) GuildMemberRankList(context.Context, *GuildMemberRankListReq) (*GuildMemberRankListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GuildMemberRankList not implemented")
}
func (UnimplementedRankGuildSystemServer) mustEmbedUnimplementedRankGuildSystemServer() {}
func (UnimplementedRankGuildSystemServer) testEmbeddedByValue()                         {}

// UnsafeRankGuildSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankGuildSystemServer will
// result in compilation errors.
type UnsafeRankGuildSystemServer interface {
	mustEmbedUnimplementedRankGuildSystemServer()
}

func RegisterRankGuildSystemServer(s grpc.ServiceRegistrar, srv RankGuildSystemServer) {
	// If the following call panics, it indicates UnimplementedRankGuildSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankGuildSystem_ServiceDesc, srv)
}

func _RankGuildSystem_GuildRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuildRankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankGuildSystemServer).GuildRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankGuildSystem_GuildRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankGuildSystemServer).GuildRankList(ctx, req.(*GuildRankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankGuildSystem_GuildMemberRankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuildMemberRankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankGuildSystemServer).GuildMemberRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankGuildSystem_GuildMemberRankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankGuildSystemServer).GuildMemberRankList(ctx, req.(*GuildMemberRankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RankGuildSystem_ServiceDesc is the grpc.ServiceDesc for RankGuildSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankGuildSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RankGuildApi.RankGuildSystem",
	HandlerType: (*RankGuildSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GuildRankList",
			Handler:    _RankGuildSystem_GuildRankList_Handler,
		},
		{
			MethodName: "GuildMemberRankList",
			Handler:    _RankGuildSystem_GuildMemberRankList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/RankGuildInner.proto",
}
